version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mimo-Game-server/
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 200
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
